steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/doppel-backend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/doppel-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'doppel-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/doppel-backend'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--vpc-connector'
      - 'doppel-connector'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASS}@${_DB_HOST}:5432/${_DB_NAME},FRONTEND_URL=https://doppel.app'

images:
  - 'gcr.io/$PROJECT_ID/doppel-backend'

substitutions:
  _DB_USER: postgres
  _DB_PASS: postgres
  _DB_HOST: 10.0.0.3
  _DB_NAME: doppel