steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/doppel-frontend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/doppel-frontend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'doppel-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/doppel-frontend'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--vpc-connector'
      - 'doppel-connector'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=https://api.doppel.app'

images:
  - 'gcr.io/$PROJECT_ID/doppel-frontend'